Use /usr/bin/clang directly
When using `clang` provided by nix, it will output errors:

```
c_src/mac/common.h:5:10: fatal error: 'CoreServices/CoreServices.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I think it would be better if we using the `/usr/bin/clang` bundled in macOS.

This will reduce the problems introduced by inconsistent environments, and make
new developers happier.